use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use ulpf_pack::Pack;

#[derive(Debug, Serialize, Deserialize)]
pub struct DraftResult {
    pub pack_yaml: String,
    pub model: String,
    pub fixtures: usize,
    pub fixtures_passed: usize,
}

pub fn draft_pack(raw_log: &str) -> anyhow::Result<DraftResult> {
    let mut decoders = Vec::new();
    let mut body_ref = raw_log;

    // Envelope detection
    if body_ref.starts_with('<') && body_ref.contains(">: ") {
        decoders.push("syslog".to_string());
        if let Some(idx) = body_ref.find(">: ") {
            body_ref = &body_ref[idx + 3..];
        }
    }

    // Body detection
    if body_ref.starts_with('{') {
        decoders.push("json".to_string());
    } else if body_ref.contains("CEF:") {
        decoders.push("cef".to_string());
    } else if body_ref.contains("LEEF:") {
        decoders.push("leef".to_string());
    } else if body_ref.contains('=') && body_ref.split_whitespace().all(|p| p.contains('=')) {
        decoders.push("keyvalue".to_string());
    } else if body_ref.split(',').count() > 3 {
        decoders.push("csv".to_string());
    } else {
        decoders.push("regex".to_string()); // Fallback
    }

    let mut mapping = std::collections::BTreeMap::new();
    let fields = vec![
        ("srcip", "src_endpoint.ip"),
        ("dstip", "dst_endpoint.ip"),
        ("srcport", "src_endpoint.port"),
        ("dstport", "dst_endpoint.port"),
        ("proto", "connection_info.protocol_name"),
        ("action", "activity_id"),
    ];

    for (k, v) in fields {
        mapping.insert(v.to_string(), ulpf_pack::spec::MapSpec::Field(ulpf_pack::spec::FieldSpec {
            from: ulpf_pack::spec::OneOrMany::One(k.to_string()),
            cast: None,
            format: None,
            enum_table: None,
            default: None,
            observable: None,
        }));
    }

    let mut identity = ulpf_pack::Identity {
        id: "draft-heuristic".to_string(),
        vendor: "Unknown".to_string(),
        product: "Unknown".to_string(),
        version: None,
        log_format: Some(decoders.join("-")),
        detect: vec![],
        priority: 50,
    };

    let extract = decoders.into_iter().map(|d| ulpf_pack::spec::ExtractStep {
        decoder: d,
        sep: None,
        delim: None,
        headers: vec![],
        patterns: vec![],
        optional: false,
    }).collect();

    let pack = Pack {
        identity,
        extract,
        map: mapping,
        enums: BTreeMap::new(),
        fixtures: vec![ulpf_pack::Fixture {
            raw: raw_log.to_string(),
            expect: BTreeMap::new(), // To be filled by analyst
            note: Some("Generated by heuristic".to_string()),
        }],
        provenance: None,
    };

    let pack_yaml = serde_yaml::to_string(&pack)?;

    Ok(DraftResult {
        pack_yaml,
        model: "heuristic-v1".to_string(),
        fixtures: 1,
        fixtures_passed: 0,
    })
}
